// <auto-generated />
using System;
using AliHaydarBase.Api.Dependencies;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AliHaydarBase.Api.Migrations
{
    [DbContext(typeof(AliHaydarDbContext))]
    [Migration("20260711121235_changeseedGuid")]
    partial class changeseedGuid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Blogs.BlogImages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGallery")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("BlogImages");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Blogs.Blogs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AuditLevel1Approved")
                        .HasColumnType("bit");

                    b.Property<bool>("AuditLevel2Approved")
                        .HasColumnType("bit");

                    b.Property<bool>("AuditLevel3Approved")
                        .HasColumnType("bit");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Blogs.Categories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.ClaimDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisibleToFrontend")
                        .HasColumnType("bit");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UiHint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClaimDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1bfe781-1f6a-465b-896e-6f233376b74d"),
                            Category = "Access",
                            CreatedAt = new DateTime(2025, 10, 24, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "User's assigned department",
                            Group = "Organizational",
                            IsActive = true,
                            IsVisibleToFrontend = true,
                            Scope = "UserManagement",
                            Type = "Department",
                            UiHint = "ShowDepartmentScopedUI"
                        },
                        new
                        {
                            Id = new Guid("b2bfe781-1f6a-465b-896e-6f233376b74d"),
                            Category = "Access",
                            CreatedAt = new DateTime(2025, 10, 24, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "User's security clearance level",
                            Group = "Organizational",
                            IsActive = true,
                            IsVisibleToFrontend = true,
                            Scope = "UserManagement",
                            Type = "SecurityLevel",
                            UiHint = "ShowSecurityLevelBadge"
                        },
                        new
                        {
                            Id = new Guid("c3bfe781-1f6a-465b-896e-6f233376b74d"),
                            Category = "Permission",
                            CreatedAt = new DateTime(2025, 10, 24, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permission to edit student grades",
                            Group = "Academic",
                            IsActive = true,
                            IsVisibleToFrontend = true,
                            Scope = "Academic",
                            Type = "CanEditGrades",
                            UiHint = "EnableGradeEditor"
                        });
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Members.IdCardTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("BackImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("BackLayoutJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardHeightMm")
                        .HasColumnType("int");

                    b.Property<int>("CardWidthMm")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dpi")
                        .HasColumnType("int");

                    b.Property<byte[]>("FrontImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FrontLayoutJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IdCardTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            BackLayoutJson = "{}",
                            CardHeightMm = 54,
                            CardWidthMm = 86,
                            CompanyName = "Ali Haydar Co.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dpi = 300,
                            FrontLayoutJson = "{}",
                            IsActive = true,
                            TemplateName = "Default Template",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Year = 2024
                        });
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullNameArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlockedByAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIdPrinted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastYearIdentityRenewal")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisterNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            City = "Baghdad",
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali.haydar@example.com",
                            FullNameArabic = "Ali Haydar",
                            FullNameEnglish = "",
                            Gender = "Male",
                            IdNumber = "ID-001",
                            ImageUrl = "https://randomuser.me/api/portraits/men/1.jpg",
                            IsBlockedByAdmin = false,
                            IsIdPrinted = false,
                            IssuanceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Manager",
                            LastYearIdentityRenewal = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "07700000001",
                            RegisterDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisterNumber = "REG-001",
                            Stage = "Stage 1"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            City = "Basra",
                            DateOfBirth = new DateTime(1992, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.mahmood@example.com",
                            FullNameArabic = "Sara Mahmood",
                            FullNameEnglish = "",
                            Gender = "Female",
                            IdNumber = "ID-002",
                            ImageUrl = "https://randomuser.me/api/portraits/women/2.jpg",
                            IsBlockedByAdmin = false,
                            IsIdPrinted = false,
                            IssuanceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Software Engineer",
                            LastYearIdentityRenewal = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "07700000002",
                            RegisterDate = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisterNumber = "REG-002",
                            Stage = "Stage 2"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            City = "Mosul",
                            DateOfBirth = new DateTime(1988, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.khalid@example.com",
                            FullNameArabic = "Omar Khalid",
                            FullNameEnglish = "",
                            Gender = "Male",
                            IdNumber = "ID-003",
                            ImageUrl = "https://randomuser.me/api/portraits/men/3.jpg",
                            IsBlockedByAdmin = false,
                            IsIdPrinted = false,
                            IssuanceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Accountant",
                            LastYearIdentityRenewal = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "07700000003",
                            RegisterDate = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisterNumber = "REG-003",
                            Stage = "Stage 3"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            City = "Baghdad",
                            DateOfBirth = new DateTime(1995, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lina.ahmed@example.com",
                            FullNameArabic = "Lina Ahmed",
                            FullNameEnglish = "",
                            Gender = "Female",
                            IdNumber = "ID-004",
                            ImageUrl = "https://randomuser.me/api/portraits/women/4.jpg",
                            IsBlockedByAdmin = false,
                            IsIdPrinted = false,
                            IssuanceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "HR Specialist",
                            LastYearIdentityRenewal = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "07700000004",
                            RegisterDate = new DateTime(2023, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisterNumber = "REG-004",
                            Stage = "Stage 1"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            City = "Najaf",
                            DateOfBirth = new DateTime(1991, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hassan.jabar@example.com",
                            FullNameArabic = "Hassan Jabar",
                            FullNameEnglish = "",
                            Gender = "Male",
                            IdNumber = "ID-005",
                            ImageUrl = "https://randomuser.me/api/portraits/men/5.jpg",
                            IsBlockedByAdmin = false,
                            IsIdPrinted = false,
                            IssuanceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Financial Analyst",
                            LastYearIdentityRenewal = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "07700000005",
                            RegisterDate = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisterNumber = "REG-005",
                            Stage = "Stage 2"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            City = "Karbala",
                            DateOfBirth = new DateTime(1993, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noor.zahra@example.com",
                            FullNameArabic = "Noor Al‑Zahra",
                            FullNameEnglish = "",
                            Gender = "Female",
                            IdNumber = "ID-006",
                            ImageUrl = "https://randomuser.me/api/portraits/women/6.jpg",
                            IsBlockedByAdmin = false,
                            IsIdPrinted = false,
                            IssuanceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Marketing Manager",
                            LastYearIdentityRenewal = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "07700000006",
                            RegisterDate = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisterNumber = "REG-006",
                            Stage = "Stage 3"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            City = "Baghdad",
                            DateOfBirth = new DateTime(1989, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mustafa.ali@example.com",
                            FullNameArabic = "Mustafa Ali",
                            FullNameEnglish = "",
                            Gender = "Male",
                            IdNumber = "ID-007",
                            ImageUrl = "https://randomuser.me/api/portraits/men/7.jpg",
                            IsBlockedByAdmin = false,
                            IsIdPrinted = false,
                            IssuanceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Software Developer",
                            LastYearIdentityRenewal = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "07700000007",
                            RegisterDate = new DateTime(2021, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisterNumber = "REG-007",
                            Stage = "Stage 1"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            City = "Basra",
                            DateOfBirth = new DateTime(1994, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatima.kareem@example.com",
                            FullNameArabic = "Fatima Kareem",
                            FullNameEnglish = "",
                            Gender = "Female",
                            IdNumber = "ID-008",
                            ImageUrl = "https://randomuser.me/api/portraits/women/8.jpg",
                            IsBlockedByAdmin = false,
                            IsIdPrinted = false,
                            IssuanceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Project Manager",
                            LastYearIdentityRenewal = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "07700000008",
                            RegisterDate = new DateTime(2022, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisterNumber = "REG-008",
                            Stage = "Stage 2"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            City = "Erbil",
                            DateOfBirth = new DateTime(1990, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yasir.salman@example.com",
                            FullNameArabic = "Yasir Salman",
                            FullNameEnglish = "",
                            Gender = "Male",
                            IdNumber = "ID-009",
                            ImageUrl = "https://randomuser.me/api/portraits/men/9.jpg",
                            IsBlockedByAdmin = false,
                            IsIdPrinted = false,
                            IssuanceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Business Analyst",
                            LastYearIdentityRenewal = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "07700000009",
                            RegisterDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisterNumber = "REG-009",
                            Stage = "Stage 3"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            City = "Sulaymaniyah",
                            DateOfBirth = new DateTime(1996, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rana.saeed@example.com",
                            FullNameArabic = "Rana Saeed",
                            FullNameEnglish = "",
                            Gender = "Female",
                            IdNumber = "ID-010",
                            ImageUrl = "https://randomuser.me/api/portraits/women/10.jpg",
                            IsBlockedByAdmin = false,
                            IsIdPrinted = false,
                            IssuanceDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Designer",
                            LastYearIdentityRenewal = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "07700000010",
                            RegisterDate = new DateTime(2023, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisterNumber = "REG-010",
                            Stage = "Stage 1"
                        });
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Members.TemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BackLayoutJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FrontLayoutJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TemplateVersions");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.MonitoringData.PrintHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackThumbnailBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontThumbnailBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrintedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TemplateId");

                    b.ToTable("PrintHistories");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.RefreshTokenEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f1603dc4-c2ee-4974-b8ca-1105b4f6f1b9",
                            Description = "For Not subscribed User",
                            Name = "visitor",
                            NormalizedName = "VISITOR"
                        },
                        new
                        {
                            Id = "d2f3c8a1-4b2e-4f9a-9b1c-8e3f2a7c9d11",
                            Description = "For App Admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForthName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f1613dc4-c2ee-2344-b8aa-1105b4f6f1b9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "09cb0259-1714-4576-9a22-fca5b700817e",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hay19732000@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "HAYDER",
                            LastName = "ALZEYAD",
                            LockoutEnabled = false,
                            NormalizedEmail = "HAY19732000@GMAIL.COM",
                            NormalizedUserName = "HAY19732000@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBHVJRSiK294d/4cDFS9xZ7GGNdlMo4Zqghw+JpfbTdRP4z2YlMflon/4iSVeZT//w==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "UABF5YCL37DBZSJNMXTOXZ4QMQ3BEQRS",
                            TwoFactorEnabled = false,
                            UserName = "hay19732000@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "f1613dc4-c2ee-2344-b8aa-1105b4f6f1b9",
                            RoleId = "d2f3c8a1-4b2e-4f9a-9b1c-8e3f2a7c9d11"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Blogs.BlogImages", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.Blogs.Blogs", "Blog")
                        .WithMany("Images")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Blogs.Blogs", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.Blogs.Categories", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.MonitoringData.PrintHistory", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.Members.Member", "Member")
                        .WithMany("PrintHistories")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AliHaydarBase.Api.Core.Models.Members.IdCardTemplate", null)
                        .WithMany("PrintHistories")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AliHaydarBase.Api.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Blogs.Blogs", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Blogs.Categories", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Members.IdCardTemplate", b =>
                {
                    b.Navigation("PrintHistories");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Members.Member", b =>
                {
                    b.Navigation("PrintHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
