// <auto-generated />
using System;
using AliHaydarBase.Api.Dependencies;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AliHaydarBase.Api.Migrations
{
    [DbContext(typeof(AliHaydarDbContext))]
    partial class AliHaydarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Blogs.BlogImages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGallery")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("BlogImages");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Blogs.Blogs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AuditLevel1Approved")
                        .HasColumnType("bit");

                    b.Property<bool>("AuditLevel2Approved")
                        .HasColumnType("bit");

                    b.Property<bool>("AuditLevel3Approved")
                        .HasColumnType("bit");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Blogs.Categories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.ClaimDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisibleToFrontend")
                        .HasColumnType("bit");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UiHint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClaimDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1bfe781-1f6a-465b-896e-6f233376b74d"),
                            Category = "Access",
                            CreatedAt = new DateTime(2025, 10, 24, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "User's assigned department",
                            Group = "Organizational",
                            IsActive = true,
                            IsVisibleToFrontend = true,
                            Scope = "UserManagement",
                            Type = "Department",
                            UiHint = "ShowDepartmentScopedUI"
                        },
                        new
                        {
                            Id = new Guid("b2bfe781-1f6a-465b-896e-6f233376b74d"),
                            Category = "Access",
                            CreatedAt = new DateTime(2025, 10, 24, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "User's security clearance level",
                            Group = "Organizational",
                            IsActive = true,
                            IsVisibleToFrontend = true,
                            Scope = "UserManagement",
                            Type = "SecurityLevel",
                            UiHint = "ShowSecurityLevelBadge"
                        },
                        new
                        {
                            Id = new Guid("c3bfe781-1f6a-465b-896e-6f233376b74d"),
                            Category = "Permission",
                            CreatedAt = new DateTime(2025, 10, 24, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permission to edit student grades",
                            Group = "Academic",
                            IsActive = true,
                            IsVisibleToFrontend = true,
                            Scope = "Academic",
                            Type = "CanEditGrades",
                            UiHint = "EnableGradeEditor"
                        });
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Members.IdCardTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("BackImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("BackLayoutJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardHeightMm")
                        .HasColumnType("int");

                    b.Property<int>("CardWidthMm")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dpi")
                        .HasColumnType("int");

                    b.Property<byte[]>("FrontImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FrontLayoutJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IdCardTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            BackLayoutJson = "{}",
                            CardHeightMm = 54,
                            CardWidthMm = 86,
                            CompanyName = "Ali Haydar Co.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dpi = 300,
                            FrontLayoutJson = "{}",
                            IsActive = true,
                            TemplateName = "Default Template",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Year = 2024
                        });
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastYearIdentityRenewal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisterNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            City = "Baghdad",
                            DateOfBirth = "1990-01-01",
                            Email = "ali.haydar@example.com",
                            FullName = "Ali Haydar",
                            Gender = "Male",
                            ImageUrl = "https://randomuser.me/api/portraits/men/1.jpg",
                            LastYearIdentityRenewal = "2024",
                            Phone = "07700000001",
                            RegisterNumber = "REG-001",
                            Stage = "Stage 1",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            City = "Basra",
                            DateOfBirth = "1992-03-12",
                            Email = "sara.mahmood@example.com",
                            FullName = "Sara Mahmood",
                            Gender = "Female",
                            ImageUrl = "https://randomuser.me/api/portraits/women/2.jpg",
                            LastYearIdentityRenewal = "2024",
                            Phone = "07700000002",
                            RegisterNumber = "REG-002",
                            Stage = "Stage 2",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            City = "Mosul",
                            DateOfBirth = "1988-07-21",
                            Email = "omar.khalid@example.com",
                            FullName = "Omar Khalid",
                            Gender = "Male",
                            ImageUrl = "https://randomuser.me/api/portraits/men/3.jpg",
                            LastYearIdentityRenewal = "2023",
                            Phone = "07700000003",
                            RegisterNumber = "REG-003",
                            Stage = "Stage 3",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            City = "Baghdad",
                            DateOfBirth = "1995-11-05",
                            Email = "lina.ahmed@example.com",
                            FullName = "Lina Ahmed",
                            Gender = "Female",
                            ImageUrl = "https://randomuser.me/api/portraits/women/4.jpg",
                            LastYearIdentityRenewal = "2024",
                            Phone = "07700000004",
                            RegisterNumber = "REG-004",
                            Stage = "Stage 1",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            City = "Najaf",
                            DateOfBirth = "1991-09-14",
                            Email = "hassan.jabar@example.com",
                            FullName = "Hassan Jabar",
                            Gender = "Male",
                            ImageUrl = "https://randomuser.me/api/portraits/men/5.jpg",
                            LastYearIdentityRenewal = "2022",
                            Phone = "07700000005",
                            RegisterNumber = "REG-005",
                            Stage = "Stage 2",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            City = "Karbala",
                            DateOfBirth = "1993-02-18",
                            Email = "noor.zahra@example.com",
                            FullName = "Noor Al‑Zahra",
                            Gender = "Female",
                            ImageUrl = "https://randomuser.me/api/portraits/women/6.jpg",
                            LastYearIdentityRenewal = "2024",
                            Phone = "07700000006",
                            RegisterNumber = "REG-006",
                            Stage = "Stage 3",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            City = "Baghdad",
                            DateOfBirth = "1989-06-30",
                            Email = "mustafa.ali@example.com",
                            FullName = "Mustafa Ali",
                            Gender = "Male",
                            ImageUrl = "https://randomuser.me/api/portraits/men/7.jpg",
                            LastYearIdentityRenewal = "2023",
                            Phone = "07700000007",
                            RegisterNumber = "REG-007",
                            Stage = "Stage 1",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            City = "Basra",
                            DateOfBirth = "1994-04-22",
                            Email = "fatima.kareem@example.com",
                            FullName = "Fatima Kareem",
                            Gender = "Female",
                            ImageUrl = "https://randomuser.me/api/portraits/women/8.jpg",
                            LastYearIdentityRenewal = "2024",
                            Phone = "07700000008",
                            RegisterNumber = "REG-008",
                            Stage = "Stage 2",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            City = "Erbil",
                            DateOfBirth = "1990-12-10",
                            Email = "yasir.salman@example.com",
                            FullName = "Yasir Salman",
                            Gender = "Male",
                            ImageUrl = "https://randomuser.me/api/portraits/men/9.jpg",
                            LastYearIdentityRenewal = "2024",
                            Phone = "07700000009",
                            RegisterNumber = "REG-009",
                            Stage = "Stage 3",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            City = "Sulaymaniyah",
                            DateOfBirth = "1996-08-17",
                            Email = "rana.saeed@example.com",
                            FullName = "Rana Saeed",
                            Gender = "Female",
                            ImageUrl = "https://randomuser.me/api/portraits/women/10.jpg",
                            LastYearIdentityRenewal = "2023",
                            Phone = "07700000010",
                            RegisterNumber = "REG-010",
                            Stage = "Stage 1",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Members.PrintHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PrintedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PrintedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TemplateId");

                    b.ToTable("PrintHistories");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.RefreshTokenEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f1603dc4-c2ee-4974-b8ca-1105b4f6f1b9",
                            Description = "For Not subscribed User",
                            Name = "visitor",
                            NormalizedName = "VISITOR"
                        },
                        new
                        {
                            Id = "a1111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                            Description = "For App Admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForthName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "u1111111-uuuu-uuuu-uuuu-uuuuuuuuuuuu",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "09cb0259-1714-4576-9a22-fca5b700817e",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hay19732000@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "HAYDER",
                            LastName = "ALZEYAD",
                            LockoutEnabled = false,
                            NormalizedEmail = "HAY19732000@GMAIL.COM",
                            NormalizedUserName = "HAY19732000@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBHVJRSiK294d/4cDFS9xZ7GGNdlMo4Zqghw+JpfbTdRP4z2YlMflon/4iSVeZT//w==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "UABF5YCL37DBZSJNMXTOXZ4QMQ3BEQRS",
                            TwoFactorEnabled = false,
                            UserName = "hay19732000@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "u1111111-uuuu-uuuu-uuuu-uuuuuuuuuuuu",
                            RoleId = "a1111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Blogs.BlogImages", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.Blogs.Blogs", "Blog")
                        .WithMany("Images")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Blogs.Blogs", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.Blogs.Categories", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Members.PrintHistory", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.Members.Member", "Member")
                        .WithMany("PrintHistories")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AliHaydarBase.Api.Core.Models.Members.IdCardTemplate", "Template")
                        .WithMany("PrintHistories")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AliHaydarBase.Api.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AliHaydarBase.Api.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Blogs.Blogs", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Blogs.Categories", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Members.IdCardTemplate", b =>
                {
                    b.Navigation("PrintHistories");
                });

            modelBuilder.Entity("AliHaydarBase.Api.Core.Models.Members.Member", b =>
                {
                    b.Navigation("PrintHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
